# Generated by Django 4.0.3 on 2022-04-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tconst', models.TextField()),
                ('averageRating', models.FloatField()),
                ('numVotes', models.BigIntegerField()),
                ('titleType', models.TextField()),
                ('primaryTitle', models.TextField()),
                ('originalTitle', models.TextField()),
                ('startYear', models.IntegerField()),
                ('runtimeMinutes', models.IntegerField()),
                ('genres', models.TextField()),
            ],
        ),
    ]
