# Generated by Django 4.0.3 on 2022-04-04 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magiceightball', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='MotionPicture',
        ),
    ]
