# Generated by Django 4.0.3 on 2022-04-04 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magiceightball', '0002_rename_movie_motionpicture'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='motionpicture',
            table='motionPictures',
        ),
    ]
