# Generated by Django 4.0.3 on 2022-04-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magiceightball', '0003_alter_motionpicture_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motionpicture',
            old_name='averageRating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='motionpicture',
            old_name='runtimeMinutes',
            new_name='runtime',
        ),
        migrations.RenameField(
            model_name='motionpicture',
            old_name='originalTitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='motionpicture',
            old_name='primaryTitle',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='motionpicture',
            old_name='numVotes',
            new_name='votes',
        ),
        migrations.RenameField(
            model_name='motionpicture',
            old_name='startYear',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='motionpicture',
            name='titleType',
        ),
    ]
